In [3]:
import numpy as  np
# matrix

In [2]:
# np.linspace(start,stop,total number)
#evenly divides

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# identi matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# random matrix
# random single mat
np.random.rand(5)



array([0.28639328, 0.39579461, 0.89860614, 0.42375664, 0.88266945])

In [9]:
# random multi mat
np.random.rand(5,5)

array([[0.1119795 , 0.44675124, 0.71966837, 0.72035102, 0.72388376],
       [0.21394815, 0.96451537, 0.53512994, 0.59474761, 0.29611004],
       [0.76648114, 0.87800395, 0.18560294, 0.25853066, 0.96636488],
       [0.81004797, 0.91255538, 0.07294328, 0.32264854, 0.26860178],
       [0.84692438, 0.93484935, 0.91762486, 0.25053425, 0.0130867 ]])

In [10]:
# randn = random numbers
np.random.randn(5)

array([ 1.01284668, -0.00167942, -1.11073968,  1.38875503,  1.10984484])

In [11]:
np.random.randint(5,50,5)

array([13, 31, 13, 31, 33])

In [12]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
ranarr=np.random.randint(0,50,10)
ranarr

array([31, 44, 22,  2, 39, 32, 21, 21, 46, 16])

In [14]:
print(ranarr.min(),ranarr.max())


2 46


In [15]:
print(ranarr.argmin(),ranarr.argmax())
# lindex of min and max!


3 8


In [16]:
ranarr.shape

(10,)

In [17]:

arra_new=np.arange(50).reshape(5,10)
arra_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
# changes into sin value of array
np.sin(arra_new)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
         0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
        -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
         0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265]])

In [19]:
# log value of array
np.log(arra_new)

/home/desktop-obs-73/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
        2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583],
       [3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
        3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165],
       [3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
        3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ]])

In [20]:
# pandas day 2

import pandas as pd

In [21]:
lables=['a','b','c','d']
my_data=[1,2,3,4]
arr=np.array(my_data)
print(arr)
d={'a':1,'b':2,'c':3,'d':4}

[1 2 3 4]


In [22]:
# Series 1st letter caps
pd.Series(data= my_data)
# pd.Series(data={},index={})

0    1
1    2
2    3
3    4
dtype: int64

In [23]:
from numpy.random import randn

In [24]:
 df =pd.DataFrame(randn(4,5))

In [25]:
pwd

'/home/desktop-obs-73/learn'

In [1]:
# march 11
# pandas

In [26]:
np.random.seed(101)

In [29]:
df=pd.DataFrame(randn(5,4),["A","B","C","D","E"],["W","X","Y","Z"])

In [30]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [33]:
type(df["W"])

pandas.core.series.Series

In [34]:
df.W
# column

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [35]:
#  calling list column
df[["W","X"]]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [43]:
# CREATE NEW COL
df["new"]=df["W"]+df["X"]

In [44]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [45]:
# To delete col never use
# df.drop("new")
# axis (index ) have to mention

df.drop("new",axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [40]:
# df.drop("new",axis=1) still present so use ""Inplace""
df.drop("new",axis=1,inplace=True)

In [41]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [48]:
df.drop("E")
# no need to mention axis for row 

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177

In [50]:
# loc => location
df.loc["D"]
# rows also series in pandas

W      0.188695
X     -0.758872
Y     -0.933237
Z      0.955057
new   -0.570177
Name: D, dtype: float64

In [53]:
# iloc => index location
df.iloc[3]

W      0.188695
X     -0.758872
Y     -0.933237
Z      0.955057
new   -0.570177
Name: D, dtype: float64

In [54]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [56]:
# print "A" row and "Y column values"
df.loc["A","Y"]

0.9079694464765431

In [57]:
df.loc[["A","B"],["X","Y"]]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077